### ISSUE TITLE
Islands are created, but island not assigned to player

### ISSUE THREAD

**Issue by FounderHawk** [illyria-io/SkyblockX#16]
SO the issue I am running into is only OPs can play. regular players can use /is to create a new island, which it does, however once they are teleported to their island it states they are unable to build/break unless in their island. I have checked the config file and it seems that the plugin is failing to create data in the data.json file. The plugin sees the island however as the IslandTOP runs automatically and keeps counting more than one island

**Comment by prosavage** [comment]
Can you try resetting the data.json once for me?
I tried with a fresh build and I didn't seem to have any issues.

**Comment by prosavage** [comment]
@FounderHawk did you ever try this?

**Comment by prosavage** [comment]
No answer, and it's working on my end, again, just reset data.
