### ISSUE TITLE
Chest protection

### ISSUE THREAD

**Issue by unsky559** [illyria-io/SkyblockX#24]
When owner is use `/is allow-visitors true`, anybody can take items from chests.
Also need permission for admins to broke blocks on all islands, and when you implement chest protection, permission to open chests.

**Comment by prosavage** [comment]
Have you tried using the `/sbx bypass` command, it should allow you to have all block interaction/breaking permissions on any island.

**Comment by prosavage** [comment]
Should be fixed, I tested on my end.
