### ISSUE TITLE
/is top bug

### ISSUE THREAD

**Issue by unsky559** [illyria-io/SkyblockX#28]
A BRAND NEW bug special for you! 
`/is top` So, if you are creating and deleting your island many times, all of them is stored in this list

![Снимок](https://user-images.githubusercontent.com/33353900/77257993-67b8cf00-6c80-11ea-8aa2-d4802fac86b1.PNG)

**Comment by prosavage** [comment]
Yeah not a major issue as it would clear restart but an easy fix
