### ISSUE TITLE
Idea: include a WorldGuard protection plugin

### ISSUE THREAD

**Issue by unsky559** [illyria-io/SkyblockX#29]
In this version  you use your own protection on islands, but what if use WorldGuard intherd it? When island is creating you need to just create region with size of it. It has many flags and good permission system for admins. Also it would be good to add default config where admins could select what flags to allow. 
Also this will remove all teleportation( #25 ), chest ( #24 ), fly, and many others bugs.

**Comment by prosavage** [comment]
One of the things about this plugin is that it can run with zero dependencies, so this would add a dependency.

I will probably work on a custom settings system. I am just working on fixing up the core functionality and little bugs before adding more stuff that could break.
