### ISSUE TITLE
Configurable base command.

### ISSUE THREAD

**Issue by ShockCharge** [illyria-io/SkyblockX#33]
Please add a changable feature for the "/is" to "any command"
for example changing it to "/is" to "/cell" so it will be "/cell create".

Thank you! :3

**Comment by unsky559** [comment]
You can actually do it in `commands.yml` it gonna be look like:

`aliases:
  cell:
    - is $1` (original syntax view in [wiki](https://bukkit.gamepedia.com/Commands.yml))

But the original command `is` is still be available

**Comment by prosavage** [comment]
@ShockCharge will this solve your problem or do you want to actually disable the `/is` command too. 

I assume I would need to do something like the following to achieve a "configurable" command:
```kt
val bukkitCommandMap: Field = Bukkit.getServer().javaClass.getDeclaredField("commandMap")
bukkitCommandMap.setAccessible(true)
val commandMap: CommandMap = bukkitCommandMap.get(Bukkit.getServer()) as CommandMap
commandMap.register("seen", CommandSeen("seen"))
```

**Comment by prosavage** [comment]
I did not mean to close it.
