### ISSUE TITLE
Specific items and blocks may break the structure files

### ISSUE THREAD

**Issue by didkoti** [illyria-io/SkyblockX#36]
### Items completely break the structure files, while some of the blocks just don't generate.

**Blocks that doesn't generate correctly (bugged, mostly with wrong/default position/facing):**
Most of the slabs, 

**Known blocks:**
Nether Brick Stairs
Nether Brick Slab
Nether Wart Block
Nether Quartz Ore
Red Nether Bricks
Red Nether Slab
Stone Slab

**Known items:**
Enchanted Golden Apple
Totem of Undying

And most of the new blocks (1.14.4+)

**Error Code:**
https://hasteb.in/mazajowa.sql
https://hasteb.in/sokuzola.sql

Edit #1: Renamed the issue and added some blocks

**Comment by prosavage** [comment]
Let's use https://hasteb.in for the stack traces.
Or a code block

**Comment by unsky559** [comment]
This was fixed it in #21 PR. 
- Do you sure that you use a last available build of plugin? 
- Can you paste/save your structure whithout this items?

**Comment by didkoti** [comment]
> This was fixed it in #21 PR.
> 
> * Do you sure that you use a last available build of plugin?
> * Can you paste/save your structure whithout this items?

I already pasted it without them, but it doesn't make them fixed tho. And yes, I have the very last build of the plugin. I don't think the issue is fixed.

**Comment by prosavage** [comment]
Can you send us the breaking structure files? @ItzDidoko

**Comment by didkoti** [comment]
Well, I removed the items that can break the structure, but I can send you the one with the blocks that don't generate.
Also, I didn't know there was a new release on discord. It may have fixed the item problems, I can't check about it because I already replaced them. Sorry.

Posted the structure file in the support channel in discord

**Comment by unsky559** [comment]
![2020-03-31_01 27 41](https://user-images.githubusercontent.com/33353900/77968017-fcf63c00-72ee-11ea-86ed-eab3c7fff44f.png)
I don't know why, but it is look like some blocks is not exists in library. For example, here is just gray wool does not pasted, purple and white is ok. Susessfuly pasted all types of wood, but not Dark Oak. So strange...

**Comment by prosavage** [comment]
@unsky559 We might need to work on making that normalize method better since it is having trouble parsing some blocks.

**Comment by prosavage** [comment]
@ItzDidoko Did you check with the latest build.

**Comment by didkoti** [comment]
> @ItzDidoko Did you check with the latest build.

Yeah the problem is fixed! Thanks!
