### ISSUE TITLE
Island falling into void

### ISSUE THREAD

**Issue by michaelsieminski** [illyria-io/SkyblockX#54]
Hello,
when you fall into void from your island and get teleported back you land inside of the Tree stuck and get spammed with the "You fell into the void" message

**Comment by unsky559** [comment]
It actually teleport you to default home position, but now player can change it to another using `/is set-go` - @ProSavage need to fix

Also you can enable `"useFallingDeathCommands": true` in your config, and write something like

     "fallingDeathPreventionCommands": [
         "is go"
       ]
to add commands when player is falling

**Comment by prosavage** [comment]
Uses the go position now by default
