### ISSUE TITLE
Problem with Position Stairs

### ISSUE THREAD

**Issue by Euphillya** [illyria-io/SkyblockX#57]
Hello, I detected an orientation problem with the stairs in schematic. All stairs are 1 direction and its broken with water mecanic

**Comment by Stampede2011** [comment]
Having the same issue but even more with some other blocks. Assuming all of these issues are interconnected but below are all the blocks I can confirm have saving/pasting issues:
- Stairs
- Slabs
- Chest facing direction
- Leaves (they decay)
- Signs (text and direction)
- Fences/Walls/Panes don't connect in places
- Crops don't save their growth
- Grass under snow (doesn't have the snowy look)
- Buttons/Levers
- Trapdoors/Door
