### ISSUE TITLE
is remove

### ISSUE THREAD

**Issue by BartBarends** [illyria-io/SkyblockX#70]
You can /is remove your own team members, which won't do anything. It will simply TP them back to your island
![image](https://user-images.githubusercontent.com/55838233/86971846-2e926500-c172-11ea-8af7-b0e15de92a5a.png)

**Comment by prosavage** [comment]
yeah /is kick is for kicking team members.
I guess I can make it say something like you cannot remove a member, you must kick them from your island.

**Comment by BartBarends** [comment]
Sounds good. It seems weird to let a command do nothing basically
